# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sirodoht
email: theodorekeloglou@gmail.com
description: "Theodore Keloglou, software developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sirodoht.xyz" # the base hostname & protocol for your site
repo: "https://github.com/sirodoht/sirodoht.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /blog/:title/

# Sitemap generation
# @see https://github.com/kinnetica/jekyll-plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/blog/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
