base_url = "https://sirodoht.com"
title = "sirodoht"
description = "Some website."
language_code = "en"
compile_sass = false
highlight_code = true
highlight_theme = "ayu-light"
generate_rss = true
rss_limit = 20
