[build]
publish = "public"
command = "https://github.com/getzola/zola/releases/download/v0.5.1/zola-v0.5.1-x86_64-unknown-linux-gnu.tar.gz | tar zxvf - && /opt/build/repo/zola build"

[context.deploy-preview]
command = "https://github.com/getzola/zola/releases/download/v0.5.1/zola-v0.5.1-x86_64-unknown-linux-gnu.tar.gz | tar zxvf - && /opt/build/repo/zola build --base-url $DEPLOY_PRIME_URL"
